<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NCoreUtils.Sass</RootNamespace>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <LibSassStaticLibPath Condition=" '$(LibSassStaticLibPath)' == '' And  $(RuntimeIdentifier.StartsWith('linux'))">/usr/lib/x86_64-linux-gnu/libsass.a</LibSassStaticLibPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.Sass\NCoreUtils.Sass.csproj" />
  </ItemGroup>
  <ItemGroup>
    <DirectPInvoke Include="sass" />
    <NativeLibrary Include="$(LibSassStaticLibPath)" />
  </ItemGroup>

  <!-- LINUX ONLY ************************************************************************************************** -->
  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <CppCompilerAndLinker Condition="!$(RuntimeIdentifier.Contains('aarch64'))">g++</CppCompilerAndLinker>
    <CppCompilerAndLinker Condition="$(RuntimeIdentifier.Contains('arm64'))">aarch64-linux-gnu-g++</CppCompilerAndLinker>
    <LinkStandardCPlusPlusLibrary>true</LinkStandardCPlusPlusLibrary>
  </PropertyGroup>
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <!-- HACK: passes "-static-libgcc -static-libstdc++" before other NativeLibrary items -->
    <NativeLibrary Include="-static-libgcc -static-libstdc++" />
  </ItemGroup>
  <!-- ************************************************************************************************************* -->

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

  <!-- OSX ONLY **************************************************************************************************** -->
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('osx'))">
    <LinkerArg Include="-lc++" />
  </ItemGroup>
  <!-- ************************************************************************************************************* -->

  <!-- LINUX ONLY ************************************************************************************************** -->
  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <IlcDynamicBuildPropertyDependencies>$(IlcDynamicBuildPropertyDependencies);GetStaticLibStdCppPath</IlcDynamicBuildPropertyDependencies>
    <LinkNativeDependsOn>$(LinkNativeDependsOn);RemoveDynamicLibStdCpp</LinkNativeDependsOn>
  </PropertyGroup>

  <!-- removes dynamic libstdc++.so from LinkerArg items -->
  <Target Name="RemoveDynamicLibStdCpp">
    <ItemGroup>
      <LinkerArg Remove="-lstdc++" />
      <LinkerArg Remove="--target=aarch64-linux-gnu" />
    </ItemGroup>
    <Message Text="@(LinkerArg)" />
  </Target>

  <!-- adds static libstdc++.a as NativeLibrary item -->
  <Target Name="GetStaticLibStdCppPath">
    <Message Text="COMPILER = $(CppCompilerAndLinker)" Importance="High" />
    <Exec Command="$(CppCompilerAndLinker) -print-file-name=libstdc++.a" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="_StaticLibStdCppPath" />
    </Exec>
    <Message Text="RID = $(RuntimeIdentifier)" Importance="High" />
    <ItemGroup>
      <NativeLibrary Include="$(_StaticLibStdCppPath)" />
    </ItemGroup>
  </Target>
  <!-- ************************************************************************************************************* -->
</Project>
