<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NCoreUtils.Sass</RootNamespace>
    <PublishAot>true</PublishAot>
    <!-- <CppCompilerAndLinker>g++</CppCompilerAndLinker> -->
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.Sass\NCoreUtils.Sass.csproj" />
  </ItemGroup>
  <ItemGroup>
    <DirectPInvoke Include="sass" />
  </ItemGroup>
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('win'))">
    <NativeLibrary Include="sass.lib"  />
  </ItemGroup>
  <!--
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <NativeLibrary Include="/usr/lib/x86_64-linux-gnu/libsass.so" Condition="Exists('/usr/lib/x86_64-linux-gnu/libsass.so')" />
  </ItemGroup>
  -->
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <NativeLibrary Include="/usr/lib/x86_64-linux-gnu/libsass.a" Condition="Exists('/usr/lib/x86_64-linux-gnu/libsass.a')" />
    <!--<LinkerArg Include="-lstdc++" />-->
    <ExtraLinkerArg Include="-lstdc++" />
  </ItemGroup>
</Project>
