<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <!-- Suppresses the warnings about the package not having assemblies in lib/*/.dll.-->
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <!-- Change the default location where NuGet will put the build output -->
    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
  </PropertyGroup>
  <ItemGroup>
    <!-- pack the props files -->
    <Content Include="build\*" PackagePath="build\" />
    <Content Include="buildMultiTargeting\*" PackagePath="buildMultiTargeting\" />
  </ItemGroup>
  <ItemGroup>
    <!-- pack linux-x64 binary -->
    <None Include="tools/linux-x64/NCoreUtils.Sass.MSBuild.Runner">
      <Pack>true</Pack>
      <PackagePath>tools/linux-x64</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- pack linux-arm64 binary -->
    <None Include="tools/linux-arm64/NCoreUtils.Sass.MSBuild.Runner">
      <Pack>true</Pack>
      <PackagePath>tools/linux-arm64</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- pack osx-x64 binary -->
    <None Include="tools/osx-x64/NCoreUtils.Sass.MSBuild.Runner">
      <Pack>true</Pack>
      <PackagePath>tools/osx-x64</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- pack osx-arm64 binary -->
    <None Include="tools/osx-arm64/NCoreUtils.Sass.MSBuild.Runner">
      <Pack>true</Pack>
      <PackagePath>tools/osx-arm64</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- pack win-x64 binary -->
    <None Include="tools/win-x64/NCoreUtils.Sass.MSBuild.Runner.exe">
      <Pack>true</Pack>
      <PackagePath>tools/win-x64</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="16.5.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.5.0" PrivateAssets="All" />
  </ItemGroup>
</Project>
